# -*- coding: utf-8 -*-
"""Python&R.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EYBRhz9wVpvL7Sa8aaQ2xtXiKKLcZs51
"""

import math

# ============================================================
# VETOR PRINCIPAL (lista de dicionários)
# ============================================================
culturas = []
contador_id = 1

# ============================================================
# FUNÇÕES AUXILIARES
# ============================================================
def exibir_menu():
    print("\n" + "="*50)
    print("🌱 SISTEMA DE GESTÃO DE CULTURAS - AMAZONAS")
    print("="*50)
    print("1. Cadastrar nova cultura")
    print("2. Listar todas as culturas")
    print("3. Atualizar uma cultura")
    print("4. Deletar uma cultura")
    print("5. Sair")
    print("="*50)
    return input("Escolha uma opção: ").strip()

def cadastrar_cultura():
    global contador_id
    print("\n--- CADASTRO DE CULTURA ---")
    nome = input("Nome da cultura (Mandioca ou Açaí): ").strip().capitalize()
    if nome not in ["Mandioca", "Açaí"]:
        print("❌ Cultura não reconhecida. Use 'Mandioca' ou 'Açaí'.")
        return

    # Definir geometria e insumos conforme a cultura
    if nome == "Mandioca":
        geometria = "retangulo"
        insumo_solido = "NPK"
        dosagem_solido = 300  # kg/ha
        insumo_liquido = "Defensivo"
        dosagem_liquido = 2.0  # mL/m
    else:  # Açaí
        geometria = "circulo"
        insumo_solido = "Calcário"
        dosagem_solido = 2000  # kg/ha
        insumo_liquido = "Fungicida"
        dosagem_liquido = 1.5  # mL/m

    # Entrada de parâmetros geométricos
    if geometria == "retangulo":
        comprimento = float(input("Comprimento (metros): "))
        largura = float(input("Largura (metros): "))
        area_m2 = comprimento * largura
        param1, param2 = comprimento, largura
    else:  # circulo
        raio = float(input("Raio (metros): "))
        area_m2 = math.pi * (raio ** 2)
        param1, param2 = raio, None

    area_ha = area_m2 / 10000

    # Entrada para insumo líquido (ruas)
    num_ruas = int(input("Número de ruas (fileiras): "))
    comp_rua = float(input("Comprimento médio de cada rua (m): "))
    comp_total = num_ruas * comp_rua

    # Cálculo das quantidades
    qtd_solido_kg = area_ha * dosagem_solido
    qtd_liquido_ml = comp_total * dosagem_liquido
    qtd_liquido_l = qtd_liquido_ml / 1000

    # Monta o dicionário
    cultura = {
        "id": contador_id,
        "nome": nome,
        "geometria": geometria,
        "param1": param1,
        "param2": param2,
        "area_m2": area_m2,
        "area_ha": area_ha,
        "insumo_solido": insumo_solido,
        "dosagem_solido_kg_ha": dosagem_solido,
        "qtd_solido_kg": qtd_solido_kg,
        "insumo_liquido": insumo_liquido,
        "dosagem_liquido_ml_m": dosagem_liquido,
        "num_ruas": num_ruas,
        "comp_rua_m": comp_rua,
        "comp_total_m": comp_total,
        "qtd_liquido_ml": qtd_liquido_ml,
        "qtd_liquido_l": qtd_liquido_l
    }

    culturas.append(cultura)
    print(f"✅ Cultura '{nome}' cadastrada com ID {contador_id}.")
    contador_id += 1

def listar_culturas():
    if not culturas:
        print("\n📭 Nenhuma cultura cadastrada ainda.")
        return
    print("\n--- LISTA DE CULTURAS ---")
    for c in culturas:
        print(f"\nID: {c['id']} | {c['nome']}")
        print(f"  Geometria: {c['geometria']} | Área: {c['area_m2']:.2f} m² ({c['area_ha']:.4f} ha)")
        print(f"  Insumo sólido: {c['insumo_solido']} - {c['qtd_solido_kg']:.2f} kg")
        print(f"  Insumo líquido: {c['insumo_liquido']} - {c['qtd_liquido_l']:.2f} L (ruas: {c['num_ruas']} x {c['comp_rua_m']}m = {c['comp_total_m']:.1f}m)")

def atualizar_cultura():
    if not culturas:
        print("\n📭 Nenhuma cultura cadastrada.")
        return
    try:
        id_alvo = int(input("Digite o ID da cultura a atualizar: "))
    except ValueError:
        print("❌ ID inválido.")
        return

    for i, c in enumerate(culturas):
        if c['id'] == id_alvo:
            print(f"Atualizando cultura ID {id_alvo} ({c['nome']})")
            # Permite atualizar apenas alguns campos (simplificado: área e ruas)
            novo_comprimento = input(f"Novo comprimento (atual {c['param1']}): ")
            if novo_comprimento:
                c['param1'] = float(novo_comprimento)
            if c['geometria'] == "retangulo":
                nova_largura = input(f"Nova largura (atual {c['param2']}): ")
                if nova_largura:
                    c['param2'] = float(nova_largura)
                c['area_m2'] = c['param1'] * c['param2']
            else:
                c['area_m2'] = math.pi * (c['param1'] ** 2)
            c['area_ha'] = c['area_m2'] / 10000

            # Recalcular quantidades
            c['qtd_solido_kg'] = c['area_ha'] * c['dosagem_solido_kg_ha']
            novo_num_ruas = input(f"Novo número de ruas (atual {c['num_ruas']}): ")
            if novo_num_ruas:
                c['num_ruas'] = int(novo_num_ruas)
            novo_comp_rua = input(f"Novo comprimento de rua (atual {c['comp_rua_m']}): ")
            if novo_comp_rua:
                c['comp_rua_m'] = float(novo_comp_rua)
            c['comp_total_m'] = c['num_ruas'] * c['comp_rua_m']
            c['qtd_liquido_ml'] = c['comp_total_m'] * c['dosagem_liquido_ml_m']
            c['qtd_liquido_l'] = c['qtd_liquido_ml'] / 1000

            print("✅ Cultura atualizada com sucesso!")
            return
    print("❌ ID não encontrado.")

def deletar_cultura():
    if not culturas:
        print("\n📭 Nenhuma cultura cadastrada.")
        return
    try:
        id_alvo = int(input("Digite o ID da cultura a deletar: "))
    except ValueError:
        print("❌ ID inválido.")
        return

    for i, c in enumerate(culturas):
        if c['id'] == id_alvo:
            confirm = input(f"Tem certeza que deseja deletar a cultura '{c['nome']}' (ID {id_alvo})? (s/N): ").lower()
            if confirm == 's':
                del culturas[i]
                print("✅ Cultura deletada.")
            else:
                print("Operação cancelada.")
            return
    print("❌ ID não encontrado.")

# ============================================================
# PROGRAMA PRINCIPAL
# ============================================================
def main():
    while True:
        opcao = exibir_menu()
        if opcao == "1":
            cadastrar_cultura()
        elif opcao == "2":
            listar_culturas()
        elif opcao == "3":
            atualizar_cultura()
        elif opcao == "4":
            deletar_cultura()
        elif opcao == "5":
            print("\n👋 Saindo...")
            break
        else:
            print("❌ Opção inválida. Tente novamente.")

if __name__ == "__main__":
    main()